[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram",
    "fastapi[standard,standart]",
    "langchain",
    "langchain-mistralai",
    "langgraph",
    "mistralai",
    "python-multipart",
    "python-dotenv",
    "uvicorn",
    "docker>=7.1.0",
]
